### ISSUE TITLE
Learn MERN Stack-Hector

### ISSUE THREAD

**Issue by dan-castillo** [dan-castillo/Paynallitest#2]
this is the task to track the EPIC as there will be many individual task that are needed to "learn" the MERN stack

**Comment by arkzky** [comment]
This MERN Stack Training Course consists of 13 Sections, where the main focus is to build a template with ultimate authentication.

- [ ] Section 1: Course Introduction
- [ ] Section 2: Getting Started
- [ ] Section 3: Node Js API
- [ ] Section 4: Node Js Signin / Signup / Email Confirmation
- [ ] Section 5: React
- [ ] Section 6: React Signup / Signin / Activation
- [ ] Section 7: Private / Admin Routing
- [ ] Section 8: User Profile
- [ ] Section 9: Forgot / Reset Password
- [ ] Section 10: Login with Google
- [ ] Section 11: Login with Facebook
- [ ] Section 12: Production steps
- [ ] Section 13: Deployment
